# The fading time for the player.
# A value of 3 roughly corresponds to one second of real time.
#
# Default value: 6 (~2 seconds)
interval: 6
# The coefficient of speed with which the animation (fake distance) decreases at the edges.
# The smaller the coefficient, the faster the animation (fading).
# Accepts a value in decimal fraction from 0.1 to 0.9 inclusive.
# Values greater than or equal to one are not accepted.
#
# Default value: 0.95
coefficient: 0.95